{% set name = "jupytergis-packages" %}
{% set version = "0.5.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/j/jupytergis_core/jupytergis_core-{{ version }}.tar.gz
    sha256: e83aa0d06ce6e079307abb96453c74fcb2f0ac6bfd07ec1109ccac5cdf21dc02
    folder: jupytergis_core
  - url: https://pypi.org/packages/source/j/jupytergis_lab/jupytergis_lab-{{ version }}.tar.gz
    sha256: c099f187dd94b7af49d8637e6d7c3c7f18cbae2bf74b63c1937b7d3df3f9ae4e
    folder: jupytergis_lab
  - url: https://pypi.org/packages/source/j/jupytergis_qgis/jupytergis_qgis-{{ version }}.tar.gz
    sha256: b8406ecd8ad698f3c458462184a24db6141f793f6c43538d124a82176225fc4f
    folder: jupytergis_qgis
  - url: https://pypi.org/packages/source/j/jupytergis_lite/jupytergis_lite-{{ version }}.tar.gz
    sha256: d366ede1108e52790ec819c9dabdf6cb73152c1ddb9d67d19b30ad86758d358d
    folder: jupytergis_lite
  - url: https://pypi.org/packages/source/j/jupytergis/jupytergis-{{ version }}.tar.gz
    sha256: 39fda03510c80e0fe9c222a6db318d24cfa1aceabc96cb9d83dbd86d238db019
    folder: jupytergis

build:
  noarch: python
  number: 0


outputs:
  - name: jupytergis-core
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd jupytergis_core
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - hatchling
        - yarn
        - jupyterlab >=4,<5
        - hatch-jupyter-builder
        - hatch-nodejs-version >=0.3.2
      run:
        - python >={{ python_min }}
        - jupyter_ydoc >=2,<4
    test:
      # imports:
      #   - jupytergis_core
      commands:
        - pip check
        - test -f ${PREFIX}/share/jupyter/labextensions/@jupytergis/jupytergis-core/package.json                            # [unix]
        - if not exist %PREFIX%\\share\\jupyter\\labextensions\\@jupytergis/jupytergis-core\\package.json (exit 1)          # [win]
      requires:
        - pip

  - name: jupytergis-lab
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd jupytergis_lab
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - hatchling
        - yarn
        - jupyterlab >=4,<5
        - hatch-jupyter-builder
        - hatch-nodejs-version >=0.3.2
      run:
        - python >={{ python_min }}
        - jupyter_ydoc >=2,<4
        - ypywidgets >=0.9.0,<0.10
        - yjs-widgets >=0.4,<0.5
        - comm >=0.1.2,<0.2
        - pydantic >=2,<3
        - jupytergis-core
      run_constrained:
        - jupytergis-core ={{ version }}
    test:
      imports:
        - jupytergis_lab.notebook.gis_document
      commands:
        - test -f ${PREFIX}/share/jupyter/labextensions/@jupytergis/jupytergis-lab/package.json                            # [unix]
        - if not exist %PREFIX%\\share\\jupyter\\labextensions\\@jupytergis/jupytergis-lab\\package.json (exit 1)          # [win]
      requires:
        - pip

  - name: jupytergis-qgis
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd jupytergis_qgis
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - hatchling
        - yarn
        - jupyterlab >=4,<5
        - hatch-jupyter-builder
        - hatch-nodejs-version >=0.3.2
      run:
        - python >={{ python_min }}
        - jupyter_server >=2.0.1,<3
        - jupyter_ydoc >=2,<4
        - jupytergis-core
        - jupytergis-lab
      run_constrained:
        - jupyterlab >=4,<5
        - jupytergis-lab ={{ version }}
        - jupytergis-core ={{ version }}
    test:
      imports:
        - jupytergis_qgis.qgis_loader
      requires:
        - pip
        - qgis

  - name: jupytergis-lite
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd jupytergis_lite
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - hatchling
      run:
        - python >={{ python_min }}
        - jupytergis-core
        - jupytergis-lab
        - my-jupyter-shared-drive
      run_constrained:
        - jupytergis-core ={{ version }}
        - jupytergis-lab ={{ version }}
    test:
      imports:
        - jupytergis
      requires:
        - pip
        - python {{ python_min }}

  - name: jupytergis
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd jupytergis
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - hatchling
      run:
        - python >={{ python_min }}
        - jupytergis-core
        - jupytergis-lab
        - jupytergis-qgis
        - jupyter-collaboration >=3,<4
        - jupyter-collaboration-ui >=1,<2
        - jupyter-docprovider >=1,<2
        - jupyter_server_ydoc >=1,<2
        - jupyterlab >=4.3,<5
      run_constrained:
        - jupytergis-core ={{ version }}
        - jupytergis-lab ={{ version }}
        - jupytergis-qgis ={{ version }}
    test:
      imports:
        - jupytergis
      requires:
        - pip
        - python {{ python_min }}

about:
  home: https://github.com/geojupyter/jupytergis
  summary: A JupyterLab extension for collaborative GIS
  description: |
    jupytergis is a JupyterLab extension for GIS with collaborative editing support. It is designed to allow multiple people to work on the same file at the same time, and to facilitate discussion and collaboration around the GIS visualization being created.
    jupytergis has support for QGIS files, which makes it easy to import and export models from QGIS. It also has a range of features for creating and manipulating layers.
  license: BSD-3-Clause
  license_family: BSD
  license_file: jupytergis/LICENSE
  doc_url: https://jupytergis.readthedocs.io/en/latest
  dev_url: https://github.com/geojupyter/jupytergis

extra:
  recipe-maintainers:
    - mfisher87
    - martinRenou
