{% set name = "jupytergis-packages" %}
{% set version = "0.12.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/j/jupytergis_core/jupytergis_core-{{ version }}.tar.gz
    sha256: abbfc0be8f52316b3add8ee75cdde532751ab4b527df8ebc5a88848533d0c201
    folder: jupytergis_core
  - url: https://pypi.org/packages/source/j/jupytergis_lab/jupytergis_lab-{{ version }}.tar.gz
    sha256: 7c5ebb0c1d8fdf614316fd1ae83c6cdcf3c63f21569d41ac7d22ed278a2d2ced
    folder: jupytergis_lab
  - url: https://pypi.org/packages/source/j/jupytergis_qgis/jupytergis_qgis-{{ version }}.tar.gz
    sha256: 005e059977702fd53200264475b383b5d9c8219775ac7c1036224339545f4835
    folder: jupytergis_qgis
  - url: https://pypi.org/packages/source/j/jupytergis_lite/jupytergis_lite-{{ version }}.tar.gz
    sha256: 4f0eb82d1ea312d524fd3ec70971a4f7602521bbe6367d731c5a1aae5dcab3d7
    folder: jupytergis_lite
  - url: https://pypi.org/packages/source/j/jupytergis/jupytergis-{{ version }}.tar.gz
    sha256: cbc353769d606cb9686520e22b9850d798ff59d3b308c9b3f212b4fd1dc43936
    folder: jupytergis

build:
  noarch: python
  number: 0


outputs:
  - name: jupytergis-core
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd jupytergis_core
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - hatchling
        - yarn
        - jupyterlab >=4.5.1
        - hatch-jupyter-builder
        - hatch-nodejs-version >=0.3.2
      run:
        - python >={{ python_min }}
        - jupyter_ydoc >=2,<4
      run_constrained:
        - jupyterlab >=4.5.1
    test:
      # imports:
      #   - jupytergis_core
      commands:
        - pip check
        - test -f ${PREFIX}/share/jupyter/labextensions/@jupytergis/jupytergis-core/package.json                            # [unix]
        - if not exist %PREFIX%\\share\\jupyter\\labextensions\\@jupytergis/jupytergis-core\\package.json (exit 1)          # [win]
      requires:
        - pip

  - name: jupytergis-lab
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd jupytergis_lab
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - hatchling
        - yarn
        - jupyterlab >=4.5.1
        - hatch-jupyter-builder
        - hatch-nodejs-version >=0.3.2
      run:
        - python >={{ python_min }}
        - requests
        - jupyter_ydoc >=2,<4
        - ypywidgets >=0.9.0,<0.10
        - yjs-widgets >=0.4,<0.5
        - comm >=0.1.2,<0.2
        - pydantic >=2,<3
        - jupytergis-core
        - sidecar >=0.7.0
      run_constrained:
        - jupyterlab >=4.5.1
        - jupytergis-core ={{ version }}
    test:
      imports:
        - jupytergis_lab.notebook.gis_document
      commands:
        - test -f ${PREFIX}/share/jupyter/labextensions/@jupytergis/jupytergis-lab/package.json                            # [unix]
        - if not exist %PREFIX%\\share\\jupyter\\labextensions\\@jupytergis/jupytergis-lab\\package.json (exit 1)          # [win]
      requires:
        - pip

  - name: jupytergis-qgis
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd jupytergis_qgis
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - hatchling
        - yarn
        - jupyterlab >=4.5.1
        - hatch-jupyter-builder
        - hatch-nodejs-version >=0.3.2
      run:
        - python >={{ python_min }}
        - jupyter_server >=2.0.1,<3
        - jupyter_ydoc >=2,<4
        - jupytergis-core
        - jupytergis-lab
      run_constrained:
        - jupyterlab >=4.5.1
        - jupytergis-lab ={{ version }}
        - jupytergis-core ={{ version }}
    test:
      imports:
        - jupytergis_qgis.qgis_loader
      requires:
        - pip
        - qgis

  - name: jupytergis-lite
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd jupytergis_lite
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - hatchling
      run:
        - python >={{ python_min }}
        - jupytergis-core
        - jupytergis-lab
        - my-jupyter-shared-drive>=0.2.2
      run_constrained:
        - jupytergis-core ={{ version }}
        - jupytergis-lab ={{ version }}
    test:
      imports:
        - jupytergis
      requires:
        - pip
        - python {{ python_min }}

  - name: jupytergis
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd jupytergis
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - hatchling
      run:
        - python >={{ python_min }}
        - jupytergis-core
        - jupytergis-lab
        - jupytergis-qgis
        - jupyter-collaboration >=4,<5
        - jupyter-collaboration-ui >=2,<3
        - jupyter-docprovider >=2,<3
        - jupyter_server_ydoc >=2,<3
      run_constrained:
        - jupyterlab >=4.5.1
        - jupytergis-core ={{ version }}
        - jupytergis-lab ={{ version }}
        - jupytergis-qgis ={{ version }}
    test:
      imports:
        - jupytergis
      requires:
        - pip
        - python {{ python_min }}

about:
  home: https://github.com/geojupyter/jupytergis
  summary: A JupyterLab extension for collaborative GIS
  description: |
    jupytergis is a JupyterLab extension for GIS with collaborative editing support. It is designed to allow multiple people to work on the same file at the same time, and to facilitate discussion and collaboration around the GIS visualization being created.
    jupytergis has support for QGIS files, which makes it easy to import and export models from QGIS. It also has a range of features for creating and manipulating layers.
  license: BSD-3-Clause
  license_family: BSD
  license_file: jupytergis/LICENSE
  doc_url: https://jupytergis.readthedocs.io/en/latest
  dev_url: https://github.com/geojupyter/jupytergis

extra:
  recipe-maintainers:
    - arjxn-py
    - mfisher87
    - martinRenou
