{% set name = "jupytergis-packages" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/j/jupytergis_core/jupytergis_core-{{ version }}.tar.gz
    sha256: 456ea4ee765772da5a13897940bc9a98fed02851a5b738f601312c5f549a6b51
    folder: jupytergis_core
  - url: https://pypi.org/packages/source/j/jupytergis_lab/jupytergis_lab-{{ version }}.tar.gz
    sha256: 5992eebf2c3022daa7cd99122dfc9014cf83f414e574be1b6ff818bb356d3c67
    folder: jupytergis_lab
  - url: https://pypi.org/packages/source/j/jupytergis_qgis/jupytergis_qgis-{{ version }}.tar.gz
    sha256: 6035cb3928fe01a634661b70bb902cbe388d7763c3a4e02111b8921b7ddc7213
    folder: jupytergis_qgis
  - url: https://pypi.org/packages/source/j/jupytergis/jupytergis-{{ version }}.tar.gz
    sha256: 24ec66ee7376690a870434fe3f813d0ab4fe60619f036f7d8f9773a261624da4
    folder: jupytergis

build:
  noarch: python
  number: 1


outputs:
  - name: jupytergis_core
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd jupytergis_core
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - hatchling
        - yarn
        - jupyterlab >=4,<5
        - hatch-jupyter-builder
        - hatch-nodejs-version >=0.3.2
      run:
        - python >={{ python_min }}
        - jupyter_ydoc >=2,<3
        - jupyter-collaboration >=3,<4
        - pycrdt
        - jupyter_server> =2.0.1,<3
        - requests
    test:
      imports:
        - jupytergis_core
      commands:
        - pip check
        - test -f ${PREFIX}/share/jupyter/labextensions/@jupytergis/jupytergis-core/package.json                            # [unix]
        - if not exist %PREFIX%\\share\\jupyter\\labextensions\\@jupytergis/jupytergis-core\\package.json (exit 1)          # [win]
      requires:
        - pip

  - name: jupytergis_lab
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd jupytergis_lab
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - hatchling
        - yarn
        - jupyterlab >=4,<5
        - hatch-jupyter-builder
        - hatch-nodejs-version >=0.3.2
      run:
        - python >={{ python_min }}
        - jupyter_server> =2.0.1,<3
        - jupyter_ydoc >=2,<3
        - jupyter-collaboration >=3,<4
        - ypywidgets >=0.9.0,<0.10
        - yjs-widgets >=0.3.4,<0.4
        - comm >=0.1.2,<0.2
        - pydantic >=2,<3
        - jupytergis_core
        - jupyterlab >=4,<5
        - mapbox-vector-tile
        - requests
      run_constrained:
        - jupytergis_core ={{ version }}
    test:
      imports:
        - jupytergis_lab.notebook.gis_document
      commands:
        - test -f ${PREFIX}/share/jupyter/labextensions/@jupytergis/jupytergis-lab/package.json                            # [unix]
        - if not exist %PREFIX%\\share\\jupyter\\labextensions\\@jupytergis/jupytergis-lab\\package.json (exit 1)          # [win]
      requires:
        - pip

  - name: jupytergis_qgis
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd jupytergis_qgis
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - hatchling
        - yarn
        - jupyterlab >=4,<5
        - hatch-jupyter-builder
        - hatch-nodejs-version >=0.3.2
      run:
        - python >={{ python_min }}
        - jupyter_server >=2.0.1,<3
        - jupytergis_core
        - jupytergis_lab
      run_constrained:
        - jupyterlab >=4,<5
        - jupytergis_lab ={{ version }}
        - jupytergis_core ={{ version }}
    test:
      imports:
        - jupytergis_qgis.qgis_loader
      requires:
        - pip
        - qgis

  - name: jupytergis
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd jupytergis
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - hatchling
      run:
        - python >={{ python_min }}
        - jupytergis_core
        - jupytergis_lab
        - jupytergis_qgis
      run_constrained:
        - jupytergis_core ={{ version }}
        - jupytergis_lab ={{ version }}
        - jupytergis_qgis ={{ version }}
    test:
      imports:
        - jupytergis
      requires:
        - pip
        - python {{ python_min }}

about:
  home: https://github.com/geojupyter/jupytergis
  summary: A JupyterLab extension for collaborative GIS
  description: |
    jupytergis is a JupyterLab extension for GIS with collaborative editing support. It is designed to allow multiple people to work on the same file at the same time, and to facilitate discussion and collaboration around the GIS visualization being created.
    jupytergis has support for QGIS files, which makes it easy to import and export models from QGIS. It also has a range of features for creating and manipulating layers.
  license: BSD-3-Clause
  license_family: BSD
  license_file: jupytergis/LICENSE
  doc_url: https://jupytergis.readthedocs.io/en/latest
  dev_url: https://github.com/geojupyter/jupytergis

extra:
  recipe-maintainers:
    - mfisher87
    - martinRenou
